### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by atbe** [atbe/MI-349-FS17-740-html-atom-and-basic-elements-JmL5o8#1]
## Build a résumé for a fictional character, applying for a fake (and ideally ridiculous) job

@jsiarto Can you take a look at this? It's [hosted here](https://atbe.github.io/MI-349-FS17-740-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

**Comment by atbe** [comment]
@jsiarto help, please?

**Comment by jsiarto** [comment]
Fix this line:
<h1>Description of the perpetrator 🐈</h3>
You've started with an <h1> and it needs to be an <h3>. Other than that -- this looks great.

**Comment by atbe** [comment]
@jsiarto done! Thanks.

**Comment by atbe** [comment]
@jsiarto any updates? I really want to proceed to the next assignment and it's been a week now. Thanks.

**Comment by atbe** [comment]
@jsiarto Help?

**Comment by jsiarto** [comment]
:shipit:
